-- Adicionar campos de configuração SMTP à tabela system_settings
ALTER TABLE `system_settings` 
ADD COLUMN `SMTPHOST` VARCHAR(255) NOT NULL DEFAULT 'smtp.gmail.com',
ADD COLUMN `SMTPPORT` INT NOT NULL DEFAULT 587,
ADD COLUMN `SMTPSECURE` BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN `SMTPUSER` VARCHAR(320),
ADD COLUMN `SMTPPASSWORD` TEXT;
